### ISSUE TITLE
doesnt run

### ISSUE THREAD

**Issue by dariuskis** [nlssn/gh-mjolnir#5]
Helo there, bot doesnt run with forever, i fixed downgraded version and there is no error, but doesnt work, then tryed to run normaly with node bot.js and when i try to start server it says "/bin/sh: 1: .././vhserver: not found"

**Comment by neatglyphs** [comment]
Can you provide some more information about the computer you are using? For example:

What OS are you running?
Did you use LGSM to install the Valheim server?
Where are the Valheim files located (Path)?
And where are the bot files located?

**Comment by dariuskis** [comment]
ok everything is working but what i did, first i installed bot as root in root directory, and it didint worked.
Then i installed with user vhserver in vhserver directory and only then bot was working, but that user cant install forever-monitor to turn off forever process because user vhserver is not admin.

OS ubuntu 18.04
Default vlaheim server directory /home/vhserver with vhserver user

on root bot doesnt work because server works on user vhserver

**Comment by dariuskis** [comment]
so if im using multi server i'll need multi bots, because bot doesnt coonect to seperate users?

**Comment by neatglyphs** [comment]
> ok everything is working but what i did, first i installed bot as root in root directory, and it didint worked.
> Then i installed with user vhserver in vhserver directory and only then bot was working, but that user cant install forever-monitor to turn off forever process because user vhserver is not admin.
> 
> OS ubuntu 18.04
> Default vlaheim server directory /home/vhserver with vhserver user
> 
> on root bot doesnt work because server works on user vhserver

Great that it works. I didn't really think about having to switch users to install forever. I should rewrite the installation instructions to reflect this. But I think there should be a way to be able to do the whole installation from the vhserver user.

> so if im using multi server i'll need multi bots, because bot doesnt coonect to seperate users?

That's true. I don't plan on adding support for multi server, since that's not something I will be using myself.
But as I said in another thread - I'm open to accept pull requests if you (or anyone) want's to write the code.

**Comment by neatglyphs** [comment]
Created a new issue for the installation process.

Since you got the bot up and running, I will now close this issue.
